# Generated by Django 4.0.2 on 2022-02-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vase',
            fields=[
                ('vaseRef', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('collectionName', models.CharField(blank=True, max_length=600, null=True)),
                ('previousColl', models.CharField(blank=True, max_length=600, null=True)),
                ('provenanceName', models.CharField(blank=True, max_length=600, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('diameter', models.CharField(blank=True, max_length=50, null=True)),
                ('publications', models.CharField(blank=True, max_length=700, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('fabric', models.CharField(blank=True, max_length=50, null=True)),
                ('technique', models.CharField(blank=True, max_length=50, null=True)),
                ('shapeName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('plateRef', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vase', models.ManyToManyField(to='api.Vase')),
            ],
        ),
    ]
